import os
import autogenerate_sequence_diagram

def main():
  print("before import")
  import bob
  print("after import")
  
  print("before ben 1")
  bob.ben()
  print("after ben 1")
  
  print("before ben 2")
  bob.ben()
  print("after ben 2")
  
  x = bob.Jim()
  print("before jane 1")
  x.jane(hey = 4)
  print("after jane 1")
  
  import job.jobbo
  jj = job.jobbo.Jobbo()
  print("before jj.do 1")
  jj.do(1,2,3,4)
  print("after jj.do 1")
  #
  #import job.tasteless.architecture
  #wi = job.tasteless.architecture.WildcardImports()
  #wi.import_lol()

if __name__ == "__main__":
  top_level_directory_path = os.path.dirname(os.path.abspath(__file__))
  with autogenerate_sequence_diagram.AutogeneratedSequenceDiagram(top_file_name=os.path.basename(__file__),
                                                                  top_level_directory_path=top_level_directory_path):
    main()
  
